# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8392f82fc48afa6f9957ad74e3db1e046d8f9259b282229f7dbdf6614464766488ddd8c3e3172d778965647f7947b18473405755103147123fbe8e1416e2dfff

test:
  secret_key_base: 19a40ffb6f627562f9c479a5ff2d192965bbea8641732d7c7f6b0b52a51a22b4ea688697baef4ee29e8d1dcdd5c369fd4a419da635ff98e5071675bb0bc410c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
